networks:
  easyshell:
    external: true
services:
  submission-manager:
    user: 1000:1000
    build:
      context: .
      dockerfile: ./apps/submission-manager/Dockerfile
    container_name: easyshell-dev-submission-manager
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /tmp/easyshell:/tmp/easyshell
    networks:
      - easyshell
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_MANAGER_URL: http://host.docker.internal:4000
      SESSION_MANAGER_TOKEN: token
  cron:
    build:
      context: .
      dockerfile: ./apps/cron/Dockerfile
    container_name: easyshell-dev-cron
    networks:
      - easyshell
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MUSTANG_URL: http://mustang:4000
      MUSTANG_TOKEN: token
  mustang:
    build:
      context: .
      dockerfile: ./apps/mustang/Dockerfile
    container_name: easyshell-dev-mustang
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MUSTANG_TOKEN: token
    networks:
      - easyshell
    ports:
      - 4000:4000
    volumes:
      - /tmp/easyshell:/tmp/easyshell
      - /var/run/docker.sock:/var/run/docker.sock
  website:
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
      args:
        NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
        POSTHOG_HOST: ${POSTHOG_HOST}
    container_name: easyshell-dev-website
    environment:
      POSTHOG_HOST: ${POSTHOG_HOST}
      AUTH_TRUST_HOST: true
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: secret
      NEXTAUTH_URL: http://localhost:3000
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_MANAGER_URL: http://mustang:4000
      SESSION_MANAGER_TOKEN: token
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_MAIL_FROM: ${SMTP_MAIL_FROM}
    networks:
      - easyshell
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1s
      timeout: 500ms
      retries: 3
