packages:
  - apps/submission-manager
  - apps/website
  - packages/db
  - packages/env
  - packages/data
  - packages/utils
  - scripts

allowBuilds:
  better-sqlite3: true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true

catalog:
  "@hono/node-server": ^2.0.12
  "@types/node": ^20.17.30
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  esbuild: ^0.28
  execa: ^9.5.2
  hono: ^4.12.32
  tsx: ^4.23.1
  zod: ^3.25.76
  "@t3-oss/env-core": "^0.12.0"
