CREATE TYPE "public"."queue_item_status" AS ENUM('pending', 'running', 'finished');--> statement-breakpoint
CREATE TABLE "easyshell_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "easyshell_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "easyshell_bookmark" (
	"user_id" varchar(255) NOT NULL,
	"problem_id" integer NOT NULL,
	CONSTRAINT "easyshell_bookmark_user_id_problem_id_pk" PRIMARY KEY("user_id","problem_id")
);
--> statement-breakpoint
CREATE TABLE "easyshell_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"base64" text NOT NULL,
	"uploaded_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "easyshell_images_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "easyshell_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "easyshell_submission_testcase_queue" (
	"submission_id" integer NOT NULL,
	"testcase_id" integer NOT NULL,
	"status" "queue_item_status" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "easyshell_submission_testcase" (
	"submission_id" integer NOT NULL,
	"testcase_id" integer NOT NULL,
	"stdout" text NOT NULL,
	"stderr" text NOT NULL,
	"exit_code" integer NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone NOT NULL,
	"fs" jsonb,
	"success" boolean NOT NULL,
	CONSTRAINT "easyshell_submission_testcase_submission_id_testcase_id_pk" PRIMARY KEY("submission_id","testcase_id")
);
--> statement-breakpoint
CREATE TABLE "easyshell_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"problem_id" integer NOT NULL,
	"input" text NOT NULL,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "easyshell_terminal_session_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_terminal_session_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"stdin" text NOT NULL,
	"stdout" text NOT NULL,
	"stderr" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "easyshell_terminal_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_terminal_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"problem_id" integer NOT NULL,
	"testcase_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "easyshell_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"username" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "easyshell_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "easyshell_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "easyshell_account" ADD CONSTRAINT "easyshell_account_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_bookmark" ADD CONSTRAINT "easyshell_bookmark_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_images" ADD CONSTRAINT "easyshell_images_uploaded_by_easyshell_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_session" ADD CONSTRAINT "easyshell_session_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_submission_testcase_queue" ADD CONSTRAINT "submission_testcase_queue_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."easyshell_submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_submission_testcase" ADD CONSTRAINT "submission_testcase_submission_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."easyshell_submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_submissions" ADD CONSTRAINT "easyshell_submissions_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_terminal_session_log" ADD CONSTRAINT "terminal_session_log_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."easyshell_terminal_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_terminal_session" ADD CONSTRAINT "easyshell_terminal_session_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "easyshell_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "bookmark_user_id_idx" ON "easyshell_bookmark" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "easyshell_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "terminal_session_log_session_id_idx" ON "easyshell_terminal_session_log" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "terminal_session_user_id_idx" ON "easyshell_terminal_session" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_email" ON "easyshell_user" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_email_lower" ON "easyshell_user" USING btree (lower("email"));--> statement-breakpoint
CREATE UNIQUE INDEX "idx_username" ON "easyshell_user" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_username_lower" ON "easyshell_user" USING btree (lower("username"));