CREATE TABLE "easyshell_check_result" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_check_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"problem_id" integer NOT NULL,
	"session_id" integer NOT NULL,
	"score" integer NOT NULL,
	"total" integer NOT NULL,
	"passed" boolean NOT NULL,
	"output" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "easyshell_check_result" ADD CONSTRAINT "easyshell_check_result_user_id_easyshell_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."easyshell_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "easyshell_check_result" ADD CONSTRAINT "easyshell_check_result_session_id_easyshell_terminal_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."easyshell_terminal_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "check_result_user_id_idx" ON "easyshell_check_result" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "check_result_problem_id_idx" ON "easyshell_check_result" USING btree ("problem_id");--> statement-breakpoint
CREATE INDEX "check_result_user_problem_idx" ON "easyshell_check_result" USING btree ("user_id","problem_id");