CREATE TABLE "easyshell_container" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "easyshell_container_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"image" varchar(512) NOT NULL,
	"problem" varchar(255) NOT NULL,
	"testcase" integer DEFAULT 0 NOT NULL,
	"mode" varchar(20) NOT NULL,
	"type" varchar(20) NOT NULL,
	"status" varchar(20) DEFAULT 'created' NOT NULL,
	"memory" varchar(20) DEFAULT '10m',
	"cpu" varchar(20) DEFAULT '0.1',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"claimed_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "easyshell_container_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "container_name_idx" ON "easyshell_container" USING btree ("name");--> statement-breakpoint
CREATE INDEX "container_mode_problem_testcase_idx" ON "easyshell_container" USING btree ("mode","problem","testcase","deleted_at");--> statement-breakpoint
CREATE INDEX "container_status_idx" ON "easyshell_container" USING btree ("status");