import { z } from "zod"

import {
  isLiveEnvironmentProblem,
  isStandardProblem,
  ProblemInfoSchema,
  type ProblemInfo,
} from "@easyshell/problems/schema"

import data from "./problems.autogenerated.js"

const DataSchema = z.record(
  z.string(),
  z.object({
    info: ProblemInfoSchema,
  }),
)

const parsedData = DataSchema.parse(data)

export async function getProblemInfo(problem: string): Promise<ProblemInfo> {
  const config = parsedData[problem]?.info
  if (!config) throw new Error("Problem not found")
  return config
}

export async function getProblems() {
  return Object.keys(parsedData)
}

export async function getProblemSlugFromId(problemId: number) {
  const problems = await getProblems()
  for (const problem of problems) {
    const info = await getProblemInfo(problem)
    if (info.id === problemId) {
      return info.slug
    }
  }
  throw new Error("Problem not found")
}

export type WarmPoolEntry = {
  problemSlug: string
  problemInfo: ProblemInfo
  /** For standard problems: one entry per warm testcase. For live-environment: single entry with testcaseId 0. */
  instances: Array<{ testcaseId: number; warmInstances: number }>
}

/** Get all problems that have warmInstances configured. */
export async function getWarmPoolConfig(): Promise<WarmPoolEntry[]> {
  const problems = await getProblems()
  const result: WarmPoolEntry[] = []

  for (const problem of problems) {
    const info = await getProblemInfo(problem)

    if (isStandardProblem(info)) {
      const warmTestcases = info.testcases
        .filter((tc) => tc.warmInstances && tc.warmInstances > 0)
        .map((tc) => ({
          testcaseId: tc.id,
          warmInstances: tc.warmInstances!,
        }))

      if (warmTestcases.length > 0) {
        result.push({
          problemSlug: problem,
          problemInfo: info,
          instances: warmTestcases,
        })
      }
    } else if (isLiveEnvironmentProblem(info)) {
      if (info.warmInstances && info.warmInstances > 0) {
        result.push({
          problemSlug: problem,
          problemInfo: info,
          // Live-environment problems use sentinel testcaseId=1
          // (matches the Docker image tag and the website's SENTINEL_TESTCASE_ID)
          instances: [{ testcaseId: 1, warmInstances: info.warmInstances }],
        })
      }
    }
  }

  return result
}
