import { z } from "zod"

import {
  isStandardProblem,
  ProblemInfoSchema,
  type ProblemInfo,
} from "@easyshell/problems/schema"

import data from "./problems.autogenerated.js"

const DataSchema = z.record(
  z.string(),
  z.object({
    info: ProblemInfoSchema,
  }),
)

const parsedData = DataSchema.parse(data)

export async function getProblemInfo(problem: string): Promise<ProblemInfo> {
  const config = parsedData[problem]?.info
  if (!config) throw new Error("Problem not found")
  return config
}

export async function getProblems() {
  return Object.keys(parsedData)
}

export async function getProblemSlugFromId(problemId: number) {
  const problems = await getProblems()
  for (const problem of problems) {
    const info = await getProblemInfo(problem)
    if (info.id === problemId) {
      return info.slug
    }
  }
  throw new Error("Problem not found")
}
