// @easyshell/mustang — shared library for interacting with the mustang service.
export {
  createMustangClient,
  type MustangClient,
  type CreateSessionRequest,
  type CreateSessionResponse,
  type SessionReadyResponse,
  type ExecSessionResponse,
  type CheckSessionResponse,
  type CreateSubmissionRequest,
  type CreateSubmissionResponse,
  type StandardOutput,
  type ScoreResult,
  type PollSubmissionResponse,
  type ExecResult,
  type ExecError,
  type GetOrCreateTerminalSessionResponse,
  type KillTerminalSessionsResponse,
  type SubmitCommandResponse,
  type CleanupResponse,
  type RunSubmissionResponse,
  type TerminalSessionLog,
} from "./client"
