import { beforeEach, describe, expect, it, vi } from "vitest"

// ── Mocks MUST be registered before importing the SUT ───────────────────────
// problems.ts imports `../../problems.autogenerated.js` (which ships empty in
// the repo) and validates it via `@easyshell/problems/schema`. We replace
// both with deterministic test fixtures.
vi.mock("../../problems.autogenerated.js", () => ({
  default: {
    "list-files": {
      info: {
        id: 1,
        slug: "list-files",
        title: "List Files",
        description: "",
        tags: [],
        testcases: [
          {
            id: 1,
            public: true,
            expected_stdout: "hello\n",
            expected_stderr: null,
            expected_exit_code: null,
            expected_fs: null,
          },
        ],
      },
    },
    "find-words": {
      info: {
        id: 2,
        slug: "find-words",
        title: "Find Words",
        description: "",
        tags: [],
        testcases: [
          {
            id: 1,
            public: false,
            expected_stdout: null,
            expected_stderr: null,
            expected_exit_code: null,
            expected_fs: null,
          },
        ],
      },
    },
  },
}))

// ProblemInfoSchema must behave like a real Zod schema because it is
// embedded inside `z.object({ info: ProblemInfoSchema })` in problems.ts.
// `z.any()` is a real ZodType whose parse() returns the input as-is, so it
// satisfies both the structural requirement (needs `_parse`) and the
// passthrough intent.
vi.mock("@easyshell/problems/schema", async () => {
  const { z } = await import("zod")
  return { ProblemInfoSchema: z.any() }
})

const {
  getProblemInfo,
  getProblemSlugFromId,
  getProblems,
  getPublicProblemInfo,
  getPublicTestcaseInfo,
} = await import("../../src/services/problems")

beforeEach(() => {
  // The SUT has no internal mocks to reset; this exists for forward-compat.
})

describe("getProblems", () => {
  it("returns the slugs of all parsed problems", async () => {
    expect(await getProblems()).toEqual(["list-files", "find-words"])
  })
})

describe("getProblemInfo", () => {
  it("returns the info block for an existing slug", async () => {
    const info = await getProblemInfo("list-files")
    expect(info.id).toBe(1)
    expect(info.slug).toBe("list-files")
    expect(info.title).toBe("List Files")
  })

  it("throws for an unknown slug", async () => {
    await expect(getProblemInfo("nope")).rejects.toThrow(/Problem not found/)
  })
})

describe("getProblemSlugFromId", () => {
  it("returns the slug whose info.id matches", async () => {
    expect(await getProblemSlugFromId(1)).toBe("list-files")
    expect(await getProblemSlugFromId(2)).toBe("find-words")
  })

  it("throws when no problem has the requested id", async () => {
    await expect(getProblemSlugFromId(999)).rejects.toThrow(/Problem not found/)
  })
})

describe("getPublicProblemInfo", () => {
  it("returns only the public-safe fields (no testcases)", async () => {
    const info = await getPublicProblemInfo("list-files")
    expect(info).toEqual({
      id: 1,
      slug: "list-files",
      title: "List Files",
      description: "",
      tags: [],
    })
    expect(info).not.toHaveProperty("testcases")
  })
})

describe("getPublicTestcaseInfo", () => {
  it("returns the 1 public testcase for list-files", async () => {
    const tcs = await getPublicTestcaseInfo("list-files")
    expect(tcs).toHaveLength(1)
    expect(tcs[0]).toEqual({
      id: 1,
      expected_stdout: "hello\n",
      expected_stderr: null,
      expected_exit_code: null,
      expected_fs: null,
    })
  })

  it("filters out private testcases — find-words has only a private one so returns []", async () => {
    expect(await getPublicTestcaseInfo("find-words")).toEqual([])
  })
})
