import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

import { readdir, rm, writeFile } from "fs/promises"
import { join } from "path"

const WORKFLOWS_DIR = ".github/workflows"

export function autogeneratedWorkflowPath({
  suffix,
  type,
}: {
  suffix: string
  type: "push" | "test"
}) {
  if (type === "push") {
    return `${WORKFLOWS_DIR}/autogenerated-push-${suffix}.yml`
  } else if (type === "test") {
    return `${WORKFLOWS_DIR}/autogenerated-test-${suffix}.yml`
  }
  throw new Error("Invalid type")
}

function generateTestWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: test problem (${problemSlug})

on:
  pull_request:
    paths:
      - "${workflowPath}"
      - "packages/data/problems/_data/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: corepack enable
        name: Enable corepack
      - run: pnpm install --frozen-lockfile
        name: Install dependencies
      - run: pnpm tsx scripts/problems/build.ts ${problemSlug}
      - run: pnpm tsx scripts/problems/test.ts ${problemSlug}
`
}

function generatePushWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: push problem (${problemSlug})
on:
  push:
    branches:
      - main
    paths:
      - "${workflowPath}"
      - "packages/data/problems/_data/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

concurrency:
  group: push-${problemSlug}
  cancel-in-progress: false

jobs:
  push:
    environment: registry-push
    runs-on: ubuntu-latest
    steps:
      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: \${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: \${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: \${{ vars.DOCKER_REGISTRY }}
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: corepack enable
        name: Enable corepack
      - run: pnpm install --frozen-lockfile
      - run: pnpm tsx scripts/problems/build.ts ${problemSlug}
        name: build problem
      - run: pnpm tsx scripts/problems/test.ts ${problemSlug}
        name: test problem
      - run: pnpm tsx scripts/problems/push.ts ${problemSlug}
        name: push problem
        env:
          DOCKER_REGISTRY: \${{ vars.DOCKER_REGISTRY }}
`
}

async function main() {
  const workflowsPath = join(PROJECT_ROOT, WORKFLOWS_DIR)
  try {
    const files = await readdir(workflowsPath)
    for (const file of files) {
      if (file.startsWith("autogenerated-")) {
        await rm(join(workflowsPath, file))
      }
    }
  } catch (e) {
    // Silently ignore if directory doesn't exist
  }

  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const push_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "push",
    })
    const push_workflow_fullpath = join(PROJECT_ROOT, push_workflow_path)
    const push_workflow = generatePushWorkflow(problem, push_workflow_path)
    await writeFile(push_workflow_fullpath, push_workflow)

    const test_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "test",
    })
    const test_workflow_fullpath = join(PROJECT_ROOT, test_workflow_path)
    const test_workflow = generateTestWorkflow(problem, test_workflow_path)
    await writeFile(test_workflow_fullpath, test_workflow)
  }
}

main().catch(console.error)
