import { readdir, writeFile } from "fs/promises"
import { $ } from "execa"

import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

const WORKFLOWS_DIR = ".github/workflows"

export function autogeneratedWorkflowPath({
  suffix,
  type,
}: {
  suffix: string
  type: "release" | "test"
}) {
  if (type === "release") {
    return `${WORKFLOWS_DIR}/autogenerated-release-${suffix}.yml`
  } else if (type === "test") {
    return `${WORKFLOWS_DIR}/autogenerated-test-${suffix}.yml`
  }
  throw new Error("Invalid type")
}

function generateTestWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: test problem (${problemSlug})

on:
  pull_request:
    paths:
      - "${workflowPath}"
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: pnpm/action-setup@v5
        name: setup pnpm

      - uses: actions/setup-node@v4
        name: setup node
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
        name: install dependencies

      - run: pnpm run build ${problemSlug}
        name: build problem
        working-directory: ./packages/problems

      - run: pnpm run test ${problemSlug}
        name: test problem
        working-directory: ./packages/problems
`
}

function generateReleaseWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: release problem (${problemSlug})

on:
  push:
    branches:
      - main
    paths:
      - "${workflowPath}"
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"
  workflow_call:
  workflow_dispatch: {}

concurrency:
  group: release-${problemSlug}
  cancel-in-progress: false

jobs:
  test:
    uses: ./.github/workflows/autogenerated-test-${problemSlug}.yml

  release:
    needs: [test]
    environment: registry-push
    runs-on: ubuntu-latest
    steps:
      - name: setup tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: \${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: \${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: \${{ vars.DOCKER_REGISTRY }}
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v4
        name: checkout

      - uses: pnpm/action-setup@v5
        name: setup pnpm

      - uses: actions/setup-node@v4
        name: setup node
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
        name: install dependencies

      - run: pnpm run build ${problemSlug}
        name: build problem
        working-directory: ./packages/problems

      - run: pnpm run push ${problemSlug}
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: \${{ vars.DOCKER_REGISTRY }}
`
}

async function main() {
  await $`rm -rf ${PROJECT_ROOT}/${WORKFLOWS_DIR}/autogenerated-*`

  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const release_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "release",
    })
    const release_workflow_fullpath = `${PROJECT_ROOT}/${release_workflow_path}`
    const release_workflow = generateReleaseWorkflow(
      problem,
      release_workflow_path,
    )
    await writeFile(release_workflow_fullpath, release_workflow)

    const test_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "test",
    })
    const test_workflow_fullpath = `${PROJECT_ROOT}/${test_workflow_path}`
    const test_workflow = generateTestWorkflow(problem, test_workflow_path)
    await writeFile(test_workflow_fullpath, test_workflow)
  }
}

await main()
