import { readdir, writeFile } from "fs/promises"
import { $ } from "execa"

import { getProblemInfo, getProblems } from "@easyshell/problems"
import { isLiveEnvironmentProblem } from "@easyshell/problems/schema"
import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

const WORKFLOWS_DIR = ".github/workflows"

export function autogeneratedWorkflowPath({
  suffix,
  type,
}: {
  suffix: string
  type: "push" | "test"
}) {
  if (type === "push") {
    return `${WORKFLOWS_DIR}/autogenerated-push-${suffix}.yml`
  } else if (type === "test") {
    return `${WORKFLOWS_DIR}/autogenerated-test-${suffix}.yml`
  }
  throw new Error("Invalid type")
}

function generateTestWorkflow(
  problemSlug: string,
  workflowPath: string,
  isLiveEnv: boolean,
): string {
  const extraPaths = isLiveEnv
    ? `\n      - "packages/problems/k3s-base/**"\n      - "apps/entrypoint/**"`
    : ""
  const timeout = isLiveEnv ? "\n    timeout-minutes: 15" : ""

  return `\
name: test problem (${problemSlug})

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"${extraPaths}

jobs:
  test:
    runs-on: ubuntu-latest${timeout}
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: easyshell_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/easyshell_test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        name: Install dependencies
      - run: pnpm exec drizzle-kit migrate
        name: Run database migrations
      - name: Build and start mustang
        run: |
          pnpm run cache
          pnpm run build
          MUSTANG_TOKEN=token nohup node mustang.cjs &
          sleep 2
        working-directory: ./apps/mustang
      - run: pnpm run build ${problemSlug}
        working-directory: ./packages/problems
      - run: pnpm run test ${problemSlug}
        working-directory: ./packages/problems
`
}

function generatePushWorkflow(
  problemSlug: string,
  workflowPath: string,
  isLiveEnv: boolean,
): string {
  const extraPaths = isLiveEnv
    ? `\n      - "packages/problems/k3s-base/**"\n      - "apps/entrypoint/**"`
    : ""
  const timeout = isLiveEnv ? "\n    timeout-minutes: 20" : ""

  return `\
name: push problem (${problemSlug})
on:
  push:
    branches:
      - main
    paths:
      - "${workflowPath}"
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"${extraPaths}

concurrency:
  group: push-${problemSlug}
  cancel-in-progress: false

jobs:
  push:
    environment: registry-push
    runs-on: ubuntu-latest${timeout}
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: easyshell_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/easyshell_test
    steps:
      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: \${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: \${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: \${{ vars.DOCKER_REGISTRY }}
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec drizzle-kit migrate
        name: Run database migrations
      - name: Build and start mustang
        run: |
          pnpm run cache
          pnpm run build
          MUSTANG_TOKEN=token nohup node mustang.cjs &
          sleep 2
        working-directory: ./apps/mustang
      - run: pnpm run build ${problemSlug}
        name: build problem
        working-directory: ./packages/problems
      - run: pnpm run test ${problemSlug}
        name: test problem
        working-directory: ./packages/problems
      - run: pnpm run push ${problemSlug}
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: \${{ vars.DOCKER_REGISTRY }}
`
}

async function main() {
  await $`rm -rf ${PROJECT_ROOT}/${WORKFLOWS_DIR}/autogenerated-*`

  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const info = await getProblemInfo(problem)
    const isLiveEnv = isLiveEnvironmentProblem(info)

    const push_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "push",
    })
    const push_workflow_fullpath = `${PROJECT_ROOT}/${push_workflow_path}`
    const push_workflow = generatePushWorkflow(
      problem,
      push_workflow_path,
      isLiveEnv,
    )
    await writeFile(push_workflow_fullpath, push_workflow)

    const test_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "test",
    })
    const test_workflow_fullpath = `${PROJECT_ROOT}/${test_workflow_path}`
    const test_workflow = generateTestWorkflow(
      problem,
      test_workflow_path,
      isLiveEnv,
    )
    await writeFile(test_workflow_fullpath, test_workflow)
  }
}

await main()
