import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

import { $ } from "execa"
import { readdir } from "fs/promises"
import { writeFile } from "fs/promises"

const WORKFLOWS_DIR = ".github/workflows"

export function autogeneratedWorkflowPath({
  suffix,
  type,
}: {
  suffix: string
  type: "push" | "test"
}) {
  if (type === "push") {
    return `${WORKFLOWS_DIR}/autogenerated-push-${suffix}.yml`
  } else if (type === "test") {
    return `${WORKFLOWS_DIR}/autogenerated-test-${suffix}.yml`
  }
  throw new Error("Invalid type")
}

function generateTestWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: test problem (${problemSlug})

on:
  pull_request:
    paths:
      - "${workflowPath}"
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build ${problemSlug}
        working-directory: ./packages/problems
      - run: npm run test ${problemSlug}
        working-directory: ./packages/problems
`
}

function generatePushWorkflow(
  problemSlug: string,
  workflowPath: string,
): string {
  return `\
name: push problem (${problemSlug})
on:
  push:
    branches:
      - main
    paths:
      - "${workflowPath}"
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

concurrency:
  group: push-${problemSlug}
  cancel-in-progress: false

jobs:
  push:
    environment: registry-push
    runs-on: ubuntu-latest
    steps:
      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: \${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: \${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: \${{ vars.DOCKER_REGISTRY }}
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build ${problemSlug}
        name: build problem
        working-directory: ./packages/problems
      - run: npm run test ${problemSlug}
        name: test problem
        working-directory: ./packages/problems
      - run: npm run push ${problemSlug}
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: \${{ vars.DOCKER_REGISTRY }}
`
}

async function main() {
  await $`rm -rf ${PROJECT_ROOT}/${WORKFLOWS_DIR}/autogenerated-*`

  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const push_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "push",
    })
    const push_workflow_fullpath = `${PROJECT_ROOT}/${push_workflow_path}`
    const push_workflow = generatePushWorkflow(problem, push_workflow_path)
    await writeFile(push_workflow_fullpath, push_workflow)

    const test_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "test",
    })
    const test_workflow_fullpath = `${PROJECT_ROOT}/${test_workflow_path}`
    const test_workflow = generateTestWorkflow(problem, test_workflow_path)
    await writeFile(test_workflow_fullpath, test_workflow)
  }
}

await main()
