name: test problem (grep-version)

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/grep-version/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: easyshell_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/easyshell_test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        name: Install dependencies
      - run: pnpm exec drizzle-kit migrate
        name: Run database migrations
      - name: Build and start mustang
        run: |
          pnpm run cache
          pnpm run build
          MUSTANG_TOKEN=token nohup node mustang.cjs &
          sleep 2
        working-directory: ./apps/mustang
      - run: pnpm run build grep-version
        working-directory: ./packages/problems
      - run: pnpm run test grep-version
        working-directory: ./packages/problems
