name: test problem (scale-deployment)

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/scale-deployment/**"
      - "packages/problems/env.ts"
      - "packages/utils/**"
      - "apps/submission-manager/utils.ts"
      - "packages/problems/k3s-base/**"
      - "apps/entrypoint/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        name: Install dependencies
      - name: Build and start mustang
        run: |
          pnpm run cache
          pnpm run build
          DATABASE_URL=postgresql://fake:fake@localhost:5432/fake MUSTANG_TOKEN=token nohup node mustang.cjs &
          sleep 2
        working-directory: ./apps/mustang
      - run: pnpm run build scale-deployment
        working-directory: ./packages/problems
      - run: pnpm run test scale-deployment
        working-directory: ./packages/problems
