name: release all
on:
  workflow_dispatch:
jobs:
  release-website:
    uses: ./.github/workflows/release-website.yml
    secrets: inherit

  release-coordinator:
    uses: ./.github/workflows/release-coordinator.yml
    secrets: inherit

  release-runner:
    uses: ./.github/workflows/release-runner.yml
    secrets: inherit
